const CategoryMapEN: { [key: string]: string } = {
    "CATEGORY_18_DATING":"Adult dating",
    "CATEGORY_ABORTION":"Abortion",
    "CATEGORY_ADS":"Ads",
    "CATEGORY_ADWARE":"Adware and other",
    "CATEGORY_ALCOHOL":"Alcohol",
    "CATEGORY_ANONYMIZERS":"Anonymizers",
    "CATEGORY_ANOREXIA":"Anorexia",
    "CATEGORY_APT":"APT Related",
    "CATEGORY_APT_CNC_TRACKING":"APT C&C Tracking",
    "CATEGORY_APT_SINKHOLE":"APT Sinkhole",
    "CATEGORY_ARTS":"Arts",
    "CATEGORY_ASTROLOGY_AND_ESOTERICA":"Astrology, esoterica",
    "CATEGORY_AUDIO_AND_VIDEO":"Audio, video",
    "CATEGORY_BANKS":"Banks",
    "CATEGORY_BETTING":"Online sweepstakes",
    "CATEGORY_BLOGS":"Blogs",
    "CATEGORY_BOOKS_AND_WRITING":"Books, writers",
    "CATEGORY_BOTNET_CNC":"Botnet C&C",
    "CATEGORY_BUSINESS":"Business",
    "CATEGORY_CARDS_PAYMENTS":"Payment systems",
    "CATEGORY_CASINO_CARD_GAMES":"Casino, card games",
    "CATEGORY_CHATS_FORUMS":"Chats, forums, IM",
    "CATEGORY_COMPROMISED":"Compromised",
    "CATEGORY_COMPUTERSELECTRONICS":"Computers, electronics",
    "CATEGORY_COMPUTER_GAMES":"Videogames",
    "CATEGORY_CRIMEWARE":"Crimeware",
    "CATEGORY_CRYPTOCURANDMINING":"Cryptocurrencies, mining",
    "CATEGORY_CULTURE_AND_SOCIETY":"Culture, society",
    "CATEGORY_DATING_SITES":"Dating sites",
    "CATEGORY_DISCONTENT":"Dissatisfaction",
    "CATEGORY_DISCRIMINATION":"Hate, discrimination",
    "CATEGORY_DRUGS":"Alcohol, tobacco, drugs",
    "CATEGORY_DYNAMIC_DNS":"Dynamic DNS",
    "CATEGORY_EDUCATION":"Education",
    "CATEGORY_EDUCATION_PORTALS_KNOWLEDGE_BASES":"Education portals, knowledge bases",
    "CATEGORY_ELECTRONIC_COMMERCE":"Online stores, banks, payment systems",
    "CATEGORY_EXTREMISM_RACISM":"Extremism, racism",
    "CATEGORY_FASHION_STYLE":"Fashion, style",
    "CATEGORY_FILE_SHARING":"File sharing",
    "CATEGORY_FINANCEECONOMICS":"Finance, economics",
    "CATEGORY_FISHING_HUNTING":"Fishing, hunting",
    "CATEGORY_GAMBLING":"Gambling, lotteries, sweepstakes",
    "CATEGORY_GENERAL":"General",
    "CATEGORY_GOVERNMENT_POLITICS_LAWS":"Government, politics, laws",
    "CATEGORY_HATE_AND_DISCRIMINATION":"Hate, discrimination",
    "CATEGORY_HEALTH":"Health",
    "CATEGORY_HEALTH_AND_BEAUTY":"Health, beauty, sports",
    "CATEGORY_HOBBY_AND_ENTERTAINMENT":"Hobbies, entertainment",
    "CATEGORY_HOME_AND_FAMILY":"Home, family",
    "CATEGORY_HOSTING_AND_DOMAINS":"Hosting, domains",
    "CATEGORY_HUMOUR":"Humor",
    "CATEGORY_ICS_THREAT":"ICS Threat",
    "CATEGORY_ILLEGAL_SOFTWARE":"Illegal software",
    "CATEGORY_INFECTED":"Infected",
    "CATEGORY_INFORMATIONSECURITY":"Information security",
    "CATEGORY_INFORMATION_TECHNOLOGIES":"Information technologies",
    "CATEGORY_INTERNET_COMMUNICATION_MEDIA":"Internet communication",
    "CATEGORY_INTERNET_SERVICES":"Internet services",
    "CATEGORY_JOB_SEARCH":"Job search",
    "CATEGORY_KIDSINTERNET":"Kids Internet",
    "CATEGORY_LEGISLATION":"Forbidden by regional laws",
    "CATEGORY_LGBT":"LGBT+",
    "CATEGORY_LINGERIE":"Lingerie",
    "CATEGORY_LOTTERIES":"Lotteries",
    "CATEGORY_MALICIOUS_IP":"Malicious IP",
    "CATEGORY_MALWARE":"Malware",
    "CATEGORY_MEDICAL_PHARMACY":"Medicine, pharmacy",
    "CATEGORY_MILITARY":"Military",
    "CATEGORY_MUSIC":"Music",
    "CATEGORY_NARCOTICS":"Alcohol, tobacco, drugs",
    "CATEGORY_NAT_GATEWAY":"Multi-User IP",
    "CATEGORY_NETATTACK_BRUTEFORCE":"Password Bruteforce Attempts",
    "CATEGORY_NETATTACK_DDOS":"Denial Of Service Attacks",
    "CATEGORY_NETATTACK_INTRUSION":"Intrusion Attacks",
    "CATEGORY_NETATTACK_SCAN":"Network Port Scanning",
    "CATEGORY_NEWS_MEDIA":"News media",
    "CATEGORY_NUDISM":"Nudism",
    "CATEGORY_ONLINE_SHOPS":"Online stores",
    "CATEGORY_ONLINE_SHOPS_WITH_OWN_PAYMENT":"Online stores, banks, payment systems",
    "CATEGORY_OTHER":"Other detectable software",
    "CATEGORY_PAYMENTS_SYSTEMS":"Payment systems",
    "CATEGORY_PETS_ANIMALS":"Pets, animals",
    "CATEGORY_PHISHING":"Phishing",
    "CATEGORY_POLICE_DECISION":"Police Decision",
    "CATEGORY_PORNO_AND_EROTICS":"Pornography, erotic",
    "CATEGORY_PROXY":"Proxy",
    "CATEGORY_RELIGIONS_RELIGIOUS_ASSOCIATIONS":"Religions, religious associations",
    "CATEGORY_REMOTE_ADMIN_TOOLS":"Remote administration tools",
    "CATEGORY_RENT_REAL_ESTATE_SERVICES":"Real estate",
    "CATEGORY_RESTAURANTS_CAFE_FOOD":"Restaurants, cafe, food",
    "CATEGORY_SCHOOLS_UNIVERSITIES":"Schools, universities",
    "CATEGORY_SEARCH_ENGINES_AND_SERVICES":"Search engines and services",
    "CATEGORY_SELFDAMAGE":"Self-harm, suicide",
    "CATEGORY_SEX_EDUCATION":"Sex education",
    "CATEGORY_SEX_SHOPS":"Sex shops",
    "CATEGORY_SOCIAL_NETS":"Social networks",
    "CATEGORY_SOFTWARE_AUDIO_VIDEO":"Software, audio, video",
    "CATEGORY_SPAM":"Spam",
    "CATEGORY_SPAMSITES":"Spam sites",
    "CATEGORY_SPORT_AND_SPORT_GAMES":"Sports, sport games",
    "CATEGORY_TOBACCO":"Tobacco",
    "CATEGORY_TORRENTS":"Torrents",
    "CATEGORY_TOR_EXIT_NODE":"Tor Exit Node",
    "CATEGORY_TOR_NODE":"Tor Node",
    "CATEGORY_TRANSPORTATION":"Transportation",
    "CATEGORY_TRAVEL_TRIPS":"Traveling, trips",
    "CATEGORY_TV_AND_RADIO":"TV, radio",
    "CATEGORY_UNCENSORED":"Profanity, obscenity",
    "CATEGORY_UNKNOWN":"Not categorized",
    "CATEGORY_VIOLENCE":"Violence",
    "CATEGORY_VPN":"VPN",
    "CATEGORY_WEAPONS":"Weapons, explosives, pyrotechnics",
    "CATEGORY_WEB_BASED_EMAIL":"Web-based mail",
    "CATEGORY__EMPTY":"General"
};

const CategoryMapRU: { [key: string]: string } = {
    "CATEGORY_18_DATING":"Знакомства для взрослых",
    "CATEGORY_ABORTION":"Аборты",
    "CATEGORY_ADS":"Реклама, тизерные сети",
    "CATEGORY_ADWARE":"Рекламные или другие программы",
    "CATEGORY_ALCOHOL":"Алкоголь",
    "CATEGORY_ANONYMIZERS":"Средства анонимного доступа",
    "CATEGORY_ANOREXIA":"Анорексия",
    "CATEGORY_APT":"Связанные с таргетированными атаками",
    "CATEGORY_APT_CNC_TRACKING":"Служба отслеживания APT C&C",
    "CATEGORY_APT_SINKHOLE":"APT Sinkhole",
    "CATEGORY_ARTS":"Искусство",
    "CATEGORY_ASTROLOGY_AND_ESOTERICA":"Астрология, эзотерика",
    "CATEGORY_AUDIO_AND_VIDEO":"Аудио, видео",
    "CATEGORY_BANKS":"Банки",
    "CATEGORY_BETTING":"Онлайн-тотализаторы",
    "CATEGORY_BLOGS":"Блоги",
    "CATEGORY_BOOKS_AND_WRITING":"Книги, писатели",
    "CATEGORY_BOTNET_CNC":"Botnet C&C",
    "CATEGORY_BUSINESS":"Бизнес",
    "CATEGORY_CARDS_PAYMENTS":"Платежные системы",
    "CATEGORY_CASINO_CARD_GAMES":"Казино, карточные игры",
    "CATEGORY_CHATS_FORUMS":"Чаты, форумы, IM",
    "CATEGORY_COMPROMISED":"Скомпрометированный",
    "CATEGORY_COMPUTERSELECTRONICS":"Компьютерная техника, электроника",
    "CATEGORY_COMPUTER_GAMES":"Видеоигры",
    "CATEGORY_CRIMEWARE":"ПО для финансовых преступлений",
    "CATEGORY_CRYPTOCURANDMINING":"Криптовалюты, майнинг",
    "CATEGORY_CULTURE_AND_SOCIETY":"Культура, общество",
    "CATEGORY_DATING_SITES":"Сайты знакомств",
    "CATEGORY_DISCONTENT":"Недовольство",
    "CATEGORY_DISCRIMINATION":"Ненависть, дискриминация",
    "CATEGORY_DRUGS":"Алкоголь, табак, наркотики и психотропы",
    "CATEGORY_DYNAMIC_DNS":"Динамический DNS",
    "CATEGORY_EDUCATION":"Образование",
    "CATEGORY_EDUCATION_PORTALS_KNOWLEDGE_BASES":"Образовательные порталы, базы знаний",
    "CATEGORY_ELECTRONIC_COMMERCE":"Интернет-магазины, банки, платежные системы",
    "CATEGORY_EXTREMISM_RACISM":"Экстремизм, расизм",
    "CATEGORY_FASHION_STYLE":"Мода, стиль",
    "CATEGORY_FILE_SHARING":"Файловые обменники",
    "CATEGORY_FINANCEECONOMICS":"Финансы, экономика",
    "CATEGORY_FISHING_HUNTING":"Охота, рыбалка",
    "CATEGORY_GAMBLING":"Азартные игры, лотереи, тотализаторы",
    "CATEGORY_GENERAL":"Общая категория",
    "CATEGORY_GOVERNMENT_POLITICS_LAWS":"Власть, политика, закон",
    "CATEGORY_HATE_AND_DISCRIMINATION":"Ненависть, дискриминация",
    "CATEGORY_HEALTH":"Здоровье",
    "CATEGORY_HEALTH_AND_BEAUTY":"Красота, здоровье, спорт",
    "CATEGORY_HOBBY_AND_ENTERTAINMENT":"Хобби, развлечения",
    "CATEGORY_HOME_AND_FAMILY":"Дом, семья",
    "CATEGORY_HOSTING_AND_DOMAINS":"Хостинг",
    "CATEGORY_HUMOUR":"Юмор",
    "CATEGORY_ICS_THREAT":"Угроза промышленной кибербезопасности",
    "CATEGORY_ILLEGAL_SOFTWARE":"Нелегальное ПО",
    "CATEGORY_INFECTED":"Зараженный",
    "CATEGORY_INFORMATIONSECURITY":"Информационная безопасность",
    "CATEGORY_INFORMATION_TECHNOLOGIES":"Информационные технологии",
    "CATEGORY_INTERNET_COMMUNICATION_MEDIA":"Общение в сети",
    "CATEGORY_INTERNET_SERVICES":"Интернет-сервисы",
    "CATEGORY_JOB_SEARCH":"Поиск работы",
    "CATEGORY_KIDSINTERNET":"Детский интернет",
    "CATEGORY_LEGISLATION":"Запрещено региональным законодательством",
    "CATEGORY_LGBT":"ЛГБТ+",
    "CATEGORY_LINGERIE":"Белье",
    "CATEGORY_LOTTERIES":"Лотереи",
    "CATEGORY_MALICIOUS_IP":"Вредоносные IP-адреса",
    "CATEGORY_MALWARE":"Вредоносная программа",
    "CATEGORY_MEDICAL_PHARMACY":"Медицина, фармацевтика",
    "CATEGORY_MILITARY":"Вооруженные силы",
    "CATEGORY_MUSIC":"Музыка",
    "CATEGORY_NARCOTICS":"Алкоголь, табак, наркотики и психотропы",
    "CATEGORY_NAT_GATEWAY":"Многопользовательский IP-адрес",
    "CATEGORY_NETATTACK_BRUTEFORCE":"Атаки методом подбора пароля",
    "CATEGORY_NETATTACK_DDOS":"Атаки типа 'отказ в обслуживании' (DoS)",
    "CATEGORY_NETATTACK_INTRUSION":"Вторжения",
    "CATEGORY_NETATTACK_SCAN":"Сканирование сетевых портов",
    "CATEGORY_NEWS_MEDIA":"Новостные ресурсы",
    "CATEGORY_NUDISM":"Нудизм",
    "CATEGORY_ONLINE_SHOPS":"Интернет-магазины",
    "CATEGORY_ONLINE_SHOPS_WITH_OWN_PAYMENT":"Интернет-магазины, банки, платежные системы",
    "CATEGORY_OTHER":"Другие обнаруживаемые программы",
    "CATEGORY_PAYMENTS_SYSTEMS":"Платежные системы",
    "CATEGORY_PETS_ANIMALS":"Дикие и домашние животные",
    "CATEGORY_PHISHING":"Фишинг",
    "CATEGORY_POLICE_DECISION":"Решение полиции",
    "CATEGORY_PORNO_AND_EROTICS":"Порнография, эротика",
    "CATEGORY_PROXY":"Прокси",
    "CATEGORY_RELIGIONS_RELIGIOUS_ASSOCIATIONS":"Религии, религиозные объединения",
    "CATEGORY_REMOTE_ADMIN_TOOLS":"Средства удаленного администрирования",
    "CATEGORY_RENT_REAL_ESTATE_SERVICES":"Недвижимость",
    "CATEGORY_RESTAURANTS_CAFE_FOOD":"Рестораны, еда, кафе",
    "CATEGORY_SCHOOLS_UNIVERSITIES":"Школы, университеты",
    "CATEGORY_SEARCH_ENGINES_AND_SERVICES":"Поисковые машины и сервисы",
    "CATEGORY_SELFDAMAGE":"Самоповреждение, самоубийство",
    "CATEGORY_SEX_EDUCATION":"Секс-образование",
    "CATEGORY_SEX_SHOPS":"Интим-магазины",
    "CATEGORY_SOCIAL_NETS":"Социальные сети",
    "CATEGORY_SOFTWARE_AUDIO_VIDEO":"Программное обеспечение, аудио, видео",
    "CATEGORY_SPAM":"Спам",
    "CATEGORY_SPAMSITES":"Спам-сайты",
    "CATEGORY_SPORT_AND_SPORT_GAMES":"Спорт, спортивные игры",
    "CATEGORY_TOBACCO":"Табак",
    "CATEGORY_TORRENTS":"Торренты",
    "CATEGORY_TOR_EXIT_NODE":"Выходной узел Tor",
    "CATEGORY_TOR_NODE":"Узел Tor",
    "CATEGORY_TRANSPORTATION":"Транспорт",
    "CATEGORY_TRAVEL_TRIPS":"Путешествия, поездки",
    "CATEGORY_TV_AND_RADIO":"ТВ, радио",
    "CATEGORY_UNCENSORED":"Нецензурная лексика",
    "CATEGORY_UNKNOWN":"Категория не определена",
    "CATEGORY_VIOLENCE":"Насилие",
    "CATEGORY_VPN":"VPN",
    "CATEGORY_WEAPONS":"Оружие, взрывчатые вещества, пиротехника",
    "CATEGORY_WEB_BASED_EMAIL":"Веб-почта",
    "CATEGORY__EMPTY":"Общая категория"
};

export const getCategoryLabel = (categoryCode: string, language: 'en' | 'ru'): string => {
    const r = language === 'en' ? CategoryMapEN[categoryCode] : CategoryMapRU[categoryCode];
    console.log(r);
    return r;
};
